id	property
0	6.0
1	6.36999951009909
2	6.90998897599285
3	8.0100165416986
4	6.90000876645532
5	6.9399824574684
6	7.83003182600311
7	8.50003813440381
8	8.13000599987826
9	8.05998184499234
10	9.2800061736324
11	6.45000414846935
12	8.55284196865778
13	6.07572071393812
14	6.08000196903598
15	5.85387196432176
16	7.56863623584101
17	5.27572413039921
18	7.69897000433602
19	5.61978875828839
20	7.59998036493484
21	6.90000876645532
22	7.0
23	6.90000876645532
24	8.0
25	8.19997064075587
26	8.0
27	7.79997073344623
28	6.7999981345934
29	7.10001543745061
30	7.0
31	7.59998036493484
32	7.10001543745061
33	7.4000078224159
34	7.4000078224159
35	7.89997426989214
36	7.89997426989214
37	8.0
38	7.4000078224159
39	7.0
40	7.50003813440381
41	6.69999179744619
42	7.79588001734408
43	7.79997073344623
44	7.0
45	6.59999765407205
46	6.7999981345934
47	8.95860731484178
48	8.29998893767789
49	7.29998893767789
50	7.59998036493484
51	7.19997064075587
52	6.59999765407205
53	6.90000876645532
54	6.29999760285775
55	7.19997064075587
56	6.09999903484653
57	7.0
58	7.29998893767789
59	8.29998893767789
60	6.30102999566398
61	7.30102999566398
62	7.07572071393812
63	6.74472749489669
64	6.23657200643706
65	6.49485002168009
66	5.52287874528034
67	6.49485002168009
68	6.36653154442041
69	6.0
70	8.69897000433602
71	7.69897000433602
72	9.04575749056068
73	7.69897000433602
74	7.22184874961636
75	7.52287874528034
76	6.48148606012211
77	7.0
78	7.30102999566398
79	7.09691001300806
80	6.92081875395238
81	7.30102999566398
82	7.49485002168009
83	7.79588001734408
84	7.52287874528034
85	8.39794000867204
86	7.09691001300806
87	6.85387196432176
88	8.39794000867204
89	7.92081875395238
90	7.69897000433602
91	8.34678748622466
92	9.22184874961636
93	7.30102999566398
94	7.72124639904717
95	7.0
96	8.95860731484178
97	6.85387196432176
98	9.0
99	8.69897000433602
100	7.09691001300806
101	6.30102999566398
102	7.4089353929735
103	6.69897000433602
104	6.0
105	7.79588001734408
106	6.92081875395238
107	8.61978875828839
108	5.70000050388302
109	6.59999765407205
110	6.90000876645532
111	6.19999817218203
112	6.0
113	6.90000876645532
114	7.09691001300806
115	7.88605664769316
116	7.50863830616573
117	5.25963731050576
118	8.39794000867204
119	8.52287874528034
120	7.92081875395238
121	8.09691001300806
122	7.50863830616573
123	7.74472749489669
124	9.0
125	9.0
126	8.0
127	6.45469288353418
128	4.73518217699046
129	7.51999305704285
130	8.27083521030723
131	7.82390874094432
132	7.95860731484178
133	6.14026143380285
134	6.73754891026957
135	6.87614835903291
136	5.96217524941166
137	5.76955107862173
138	6.47625353318844
139	6.84163750790475
140	7.0329202658555
141	6.69897000433602
142	7.86774031046896
143	8.14752000636314
144	8.37571790416433
145	8.50584540598156
146	7.98171569157347
147	8.08777794346758
148	8.44490555142168
149	6.09999903484653
150	6.19999817218203
151	6.90000876645532
152	6.09999903484653
153	6.09999903484653
154	6.69999179744619
155	7.10001543745061
156	6.29999760285775
157	6.29999760285775
158	7.10237290870956
159	6.74472749489669
160	6.73518217699046
161	6.55284196865778
162	6.79588001734408
163	6.74472749489669
164	6.74472749489669
165	6.58502665202918
166	0.340000000004633
167	0.309999999998622
168	0.329999999997398
169	0.290000000001156
170	0.340000000004633
171	0.320000000002395
172	0.320000000002395
173	0.320000000002395
174	0.329999999997398
175	0.299999999997636
176	0.320000000002395
177	0.290000000001156
178	0.320000000002395
179	0.290000000001156
180	0.279999999999811
181	5.47886191629596
182	5.47886191629596
183	6.58502665202918
184	6.58502665202918
185	7.50003813440381
186	7.61978875828839
187	7.07058107428571
188	7.88605664769316
189	7.48148606012211
190	8.22184874961636
191	8.39794000867204
192	6.13371266091581
193	7.55284196865778
194	7.48148606012211
195	6.60032627851896
196	7.47108329972235
197	6.85387196432176
198	6.09999903484653
199	7.29998893767789
200	6.19999817218203
201	7.59998036493484
202	7.4000078224159
203	8.50003813440381
204	8.10001543745061
205	8.0
206	6.19999817218203
207	6.7999981345934
208	6.49999693194831
209	7.4000078224159
210	7.29998893767789
211	8.0
212	8.19997064075587
213	6.49999693194831
214	6.19999817218203
215	7.59998036493484
216	7.70005709997723
217	8.19997064075587
218	6.7999981345934
219	7.10001543745061
220	8.0
221	8.19997064075587
222	8.19997064075587
223	8.20065945054642
224	8.19997064075587
225	7.4000078224159
226	6.7999981345934
227	7.59998036493484
228	8.10001543745061
229	8.19997064075587
230	6.7999981345934
231	7.4000078224159
232	7.4000078224159
233	7.4000078224159
234	6.19999817218203
235	7.19997064075587
236	8.19997064075587
237	6.7999981345934
238	7.29998893767789
239	7.59998036493484
240	7.0
241	8.10001543745061
242	8.0
243	7.89997426989214
244	8.4000078224159
245	7.4000078224159
246	6.7999981345934
247	6.0
248	7.0
249	6.59999765407205
250	6.90000876645532
251	7.50003813440381
252	8.19997064075587
253	7.50003813440381
254	6.39999691337226
255	7.19997064075587
256	7.29998893767789
257	7.10001543745061
258	6.69999179744619
259	7.19997064075587
260	7.4000078224159
261	7.4000078224159
262	6.49999693194831
263	6.59999765407205
264	6.69999179744619
265	6.90000876645532
266	7.10001543745061
267	7.29998893767789
268	6.51712641639125
269	6.70996538863748
270	5.74957999769111
271	6.43889861635094
272	5.30102999566398
273	6.3045183235098
274	5.2518119729938
275	6.04000516167158
276	5.95860731484178
277	6.14691047014813
278	5.86646109162978
279	5.33724216831843
280	6.42021640338319
281	6.65757731917779
282	5.95860731484178
283	5.0
284	5.46218090492673
285	5.50863830616573
286	5.0
287	8.18996921359416
288	6.17000191130262
289	5.11350927482752
290	8.43179827593301
291	8.16749108729376
292	8.06048074738138
293	8.19382002601611
294	6.29242982390206
295	5.48148606012211
296	5.2839966563652
297	6.53760200210104
298	6.16749108729376
299	5.72124639904717
300	5.2839966563652
301	6.03621217265444
302	6.52287874528034
303	5.65757731917779
304	6.79588001734408
305	5.67778070526608
306	7.0
307	5.44369749923271
308	4.63827216398241
309	7.30102999566398
310	6.31875876262441
311	4.83863199776503
312	5.79588001734408
313	4.60205999132796
314	5.56863623584101
315	6.65757731917779
316	4.52287874528034
317	5.95860731484178
318	5.3767507096021
319	5.76955107862173
320	5.82390874094432
321	5.67778070526608
322	6.49485002168009
323	6.90657831483776
324	5.54821356447571
325	5.50307035192679
326	6.2958494831602
327	6.29929628285498
328	5.86646109162978
329	5.96257350205938
330	5.04527520902094
331	4.84771165561694
332	5.98296666070122
333	5.85387196432176
334	7.85387196432176
335	6.54515513999149
336	6.98716277529483
337	6.43297363384094
338	6.66354026615147
339	6.76195389687121
340	7.00877392430751
341	6.36151074304536
342	7.26760624017703
343	6.03857890593355
344	6.39040559077478
345	6.43651891460559
346	6.06550154875643
347	7.25963731050576
348	6.68613277963085
349	7.16115090926274
