id	property	mw
0	6.0	447.5600000000001
1	6.36999951009909	401.2600000000001
2	6.90998897599285	405.2230000000001
3	8.0100165416986	387.2330000000001
4	6.90000876645532	415.2870000000002
5	6.9399824574684	435.70500000000015
6	7.83003182600311	437.2400000000001
7	8.50003813440381	435.70500000000015
8	8.13000599987826	419.2500000000001
9	8.05998184499234	435.70500000000015
10	9.2800061736324	437.2400000000001
11	6.45000414846935	409.24400000000014
12	8.55284196865778	322.372
13	6.07572071393812	441.45800000000014
14	6.08000196903598	441.45800000000014
15	5.85387196432176	354.48700000000014
16	7.56863623584101	360.4940000000001
17	5.27572413039921	367.4450000000001
18	7.69897000433602	430.5040000000001
19	5.61978875828839	415.4890000000001
20	7.59998036493484	446.9380000000002
21	6.90000876645532	397.9060000000001
22	7.0	369.8520000000001
23	6.90000876645532	355.8250000000001
24	8.0	392.81800000000015
25	8.19997064075587	423.2420000000001
26	8.0	378.7910000000001
27	7.79997073344623	403.8410000000002
28	6.7999981345934	375.7870000000001
29	7.10001543745061	393.7770000000001
30	7.0	393.7770000000001
31	7.59998036493484	411.7670000000001
32	7.10001543745061	429.7570000000001
33	7.4000078224159	410.23200000000014
34	7.4000078224159	410.23200000000014
35	7.89997426989214	428.22200000000015
36	7.89997426989214	428.22200000000015
37	8.0	444.6770000000002
38	7.4000078224159	341.7700000000001
39	7.0	381.83500000000026
40	7.50003813440381	367.8080000000002
41	6.69999179744619	339.75400000000013
42	7.79588001734408	403.8410000000002
43	7.79997073344623	403.8410000000002
44	7.09691001300806	380.4410000000001
45	7.88605664769316	396.4150000000001
46	7.50863830616573	384.4040000000001
47	5.25963731050576	295.408
48	8.39794000867204	432.48800000000017
49	8.52287874528034	420.47700000000015
50	7.92081875395238	406.45000000000016
51	8.09691001300806	448.4050000000001
52	7.50863830616573	436.3940000000001
53	7.74472749489669	422.3670000000001
54	9.0	422.48900000000015
55	9.0	410.4780000000001
56	8.0	396.45100000000014
57	6.45469288353418	448.5450000000002
58	4.73518217699046	320.331
59	7.51999305704285	423.44800000000026
60	8.27083521030723	431.4750000000002
61	7.82390874094432	448.48700000000025
62	7.95860731484178	415.4970000000002
63	6.14026143380285	440.52500000000026
64	6.73754891026957	448.5410000000002
65	6.87614835903291	434.5140000000002
66	5.96217524941166	448.5410000000002
67	5.76955107862173	448.5410000000002
68	6.47625353318844	400.5190000000002
69	6.84163750790475	402.4950000000002
70	7.0329202658555	441.5500000000002
71	6.69897000433602	415.52700000000016
72	7.86774031046896	425.4110000000001
73	8.14752000636314	414.49100000000016
74	8.37571790416433	400.41400000000016
75	8.50584540598156	435.5060000000002
76	7.98171569157347	440.4220000000001
77	8.08777794346758	429.5020000000001
78	8.44490555142168	415.4250000000001
79	7.0	403.8410000000002
80	6.59999765407205	389.81400000000014
81	6.7999981345934	429.87900000000025
82	8.95860731484178	352.4710000000001
83	8.29998893767789	332.7870000000001
84	7.29998893767789	330.77100000000013
85	7.59998036493484	332.78700000000003
86	7.19997064075587	346.81400000000014
87	6.59999765407205	332.7870000000001
88	6.90000876645532	331.8030000000001
89	6.29999760285775	332.7910000000001
90	7.19997064075587	415.9210000000001
91	6.09999903484653	414.9370000000002
92	7.0	414.9370000000002
93	7.29998893767789	416.90900000000016
94	8.29998893767789	365.8200000000001
95	6.30102999566398	361.426
96	7.30102999566398	361.426
97	7.07572071393812	353.325
98	6.74472749489669	355.297
99	6.23657200643706	355.297
100	6.49485002168009	355.297
101	5.52287874528034	353.325
102	6.49485002168009	339.29800000000006
103	6.36653154442041	369.324
104	6.0	369.324
105	8.69897000433602	373.4370000000002
106	7.69897000433602	361.3820000000001
107	9.04575749056068	359.41000000000014
108	7.69897000433602	362.414
109	7.22184874961636	363.3980000000001
110	7.52287874528034	365.3890000000001
111	6.48148606012211	375.4530000000001
112	7.0	379.41600000000005
113	7.30102999566398	379.41600000000005
114	7.09691001300806	367.455
115	6.92081875395238	367.455
116	7.30102999566398	361.426
117	7.49485002168009	342.4240000000001
118	7.79588001734408	328.397
119	7.52287874528034	327.39000000000004
120	8.39794000867204	325.393
121	7.09691001300806	311.366
122	6.85387196432176	389.35800000000006
123	8.39794000867204	351.38700000000006
124	7.92081875395238	355.8060000000001
125	7.69897000433602	339.35100000000006
126	8.34678748622466	339.35100000000006
127	9.22184874961636	389.35800000000006
128	7.30102999566398	350.4030000000001
129	7.72124639904717	336.37600000000003
130	7.0	365.4140000000001
131	8.95860731484178	351.38700000000006
132	6.85387196432176	337.36000000000007
133	9.0	335.38800000000003
134	8.69897000433602	339.35100000000006
135	7.09691001300806	339.35100000000006
136	6.30102999566398	339.35100000000006
137	7.4089353929735	322.34900000000005
138	6.69897000433602	322.34900000000005
139	6.0	339.42000000000024
140	7.79588001734408	325.3930000000002
141	6.92081875395238	320.37300000000005
142	8.61978875828839	321.36100000000005
143	5.70000050388302	325.459
144	6.59999765407205	350.488
145	6.90000876645532	336.461
146	6.19999817218203	322.434
147	6.0	350.488
148	6.90000876645532	350.48800000000006
149	6.51712641639125	368.5210000000001
150	6.70996538863748	369.50500000000005
151	5.74957999769111	310.427
152	6.43889861635094	428.5660000000001
153	5.30102999566398	393.52400000000006
154	6.3045183235098	424.92100000000016
155	5.2518119729938	392.53600000000006
156	6.04000516167158	410.5760000000001
157	5.95860731484178	416.6050000000001
158	6.14691047014813	394.508
159	5.86646109162978	428.9530000000001
160	5.33724216831843	424.6030000000002
161	6.42021640338319	354.487
162	6.65757731917779	354.487
163	5.95860731484178	392.53600000000006
164	5.0	410.52600000000007
165	5.46218090492673	410.52600000000007
166	5.50863830616573	410.52600000000007
167	5.0	406.5630000000002
168	8.18996921359416	401.2600000000001
169	6.17000191130262	417.2590000000002
170	6.09999903484653	322.434
171	6.19999817218203	308.407
172	6.90000876645532	364.51500000000016
173	6.09999903484653	336.461
174	6.09999903484653	322.434
175	6.69999179744619	350.48800000000006
176	7.10001543745061	398.532
177	6.29999760285775	364.51500000000016
178	6.29999760285775	295.408
179	7.10237290870956	176.21899999999997
180	6.74472749489669	176.21899999999997
181	6.73518217699046	176.21899999999997
182	6.55284196865778	176.21899999999997
183	6.79588001734408	176.21899999999997
184	6.74472749489669	176.21899999999997
185	6.74472749489669	176.21899999999997
186	6.58502665202918	176.21899999999997
187	0.340000000004633	317.8200000000001
188	0.309999999998622	329.8310000000002
189	0.329999999997398	290.794
190	0.290000000001156	338.86000000000007
191	0.340000000004633	326.831
192	0.320000000002395	297.78900000000004
193	0.320000000002395	327.83700000000005
194	0.320000000002395	290.3880000000001
195	0.329999999997398	304.4150000000001
196	0.299999999997636	353.8750000000001
197	0.320000000002395	293.39200000000005
198	0.290000000001156	311.382
199	0.320000000002395	290.38800000000015
200	0.290000000001156	369.28400000000016
201	0.279999999999811	324.83300000000014
202	5.47886191629596	306.3582035560001
203	5.47886191629596	304.34600000000006
204	6.58502665202918	176.21899999999997
205	6.58502665202918	176.21899999999997
206	7.50003813440381	433.5040000000001
207	7.61978875828839	429.5860000000001
208	7.07058107428571	437.56500000000017
209	7.88605664769316	443.61300000000017
210	7.48148606012211	440.5690000000002
211	8.22184874961636	447.57600000000014
212	8.39794000867204	443.61300000000017
213	6.13371266091581	431.5580000000002
214	7.55284196865778	435.6340000000003
215	7.48148606012211	435.6150000000001
216	6.60032627851896	415.5590000000001
217	7.47108329972235	429.5860000000001
218	6.85387196432176	183.276
219	6.09999903484653	355.77700000000004
220	7.29998893767789	381.8160000000001
221	6.19999817218203	367.789
222	7.59998036493484	382.8040000000001
223	7.4000078224159	319.78800000000007
224	8.50003813440381	330.74300000000005
225	8.10001543745061	347.79900000000004
226	8.0	344.7740000000001
227	6.19999817218203	375.7870000000001
228	6.7999981345934	353.80500000000006
229	6.49999693194831	374.7990000000001
230	7.4000078224159	380.8280000000001
231	7.29998893767789	380.828
232	8.0	378.7870000000001
233	8.19997064075587	364.7600000000001
234	6.49999693194831	393.27000000000015
235	6.19999817218203	381.816
236	7.59998036493484	381.816
237	7.70005709997723	365.7480000000001
238	8.19997064075587	381.8160000000001
239	6.7999981345934	355.8210000000001
240	7.10001543745061	364.764
241	8.0	378.7910000000001
242	8.19997064075587	401.2600000000001
243	8.19997064075587	356.81
244	8.20065945054642	356.81
245	8.19997064075587	423.2420000000001
246	7.4000078224159	341.7700000000001
247	6.7999981345934	375.7870000000001
248	7.59998036493484	382.8040000000001
249	8.10001543745061	347.79900000000004
250	8.19997064075587	381.8160000000001
251	6.7999981345934	390.8270000000001
252	7.4000078224159	342.7830000000001
253	7.4000078224159	370.8370000000001
254	7.4000078224159	356.81
255	6.19999817218203	349.79300000000006
256	7.19997064075587	350.781
257	8.19997064075587	370.8370000000001
258	6.7999981345934	370.8370000000001
259	7.29998893767789	355.82200000000006
260	7.59998036493484	339.754
261	7.0	356.81
262	8.10001543745061	340.742
263	8.0	336.39200000000005
264	7.89997426989214	390.362
265	8.4000078224159	401.261
266	7.4000078224159	340.355
267	6.7999981345934	322.365
268	6.0	371.781
269	7.0	370.79300000000006
270	6.59999765407205	382.726
271	6.90000876645532	328.75600000000003
272	7.50003813440381	342.7830000000001
273	8.19997064075587	384.8640000000001
274	7.50003813440381	370.8370000000001
275	6.39999691337226	432.9110000000001
276	7.19997064075587	421.9250000000001
277	7.29998893767789	379.88800000000015
278	7.10001543745061	441.9150000000001
279	6.69999179744619	385.8510000000001
280	7.19997064075587	439.9430000000001
281	7.4000078224159	425.9160000000001
282	7.4000078224159	425.9160000000001
283	6.49999693194831	369.8520000000001
284	6.59999765407205	406.91400000000016
285	6.69999179744619	404.9420000000002
286	6.90000876645532	321.8080000000001
287	7.10001543745061	446.9380000000002
288	7.29998893767789	446.9380000000002
289	5.11350927482752	376.4120000000001
290	8.43179827593301	445.3500000000002
291	8.16749108729376	447.3660000000001
292	8.06048074738138	448.3500000000002
293	8.19382002601611	445.44100000000014
294	6.29242982390206	361.4450000000001
295	5.48148606012211	361.4450000000001
296	5.2839966563652	362.4330000000001
297	6.53760200210104	367.4740000000001
298	6.16749108729376	426.52000000000015
299	5.72124639904717	341.4550000000001
300	5.2839966563652	331.419
301	6.03621217265444	361.467
302	6.52287874528034	347.44000000000005
303	5.65757731917779	361.467
304	6.79588001734408	395.4840000000001
305	5.67778070526608	399.4470000000001
306	7.0	411.4830000000001
307	5.44369749923271	411.4830000000001
308	4.63827216398241	411.4830000000001
309	7.30102999566398	435.50500000000017
310	6.31875876262441	270.357
311	4.83863199776503	242.303
312	5.79588001734408	256.33
313	4.60205999132796	270.357
314	5.56863623584101	270.357
315	6.65757731917779	274.32000000000005
316	4.52287874528034	274.32000000000005
317	5.95860731484178	274.32000000000005
318	5.3767507096021	246.266
319	5.76955107862173	260.293
320	5.82390874094432	260.293
321	5.67778070526608	314.263
322	6.49485002168009	302.374
323	6.90657831483776	360.4350000000001
324	5.54821356447571	374.4620000000001
325	5.50307035192679	400.50000000000006
326	6.2958494831602	374.4620000000001
327	6.29929628285498	414.4050000000001
328	5.86646109162978	386.47300000000007
329	5.96257350205938	404.4880000000003
330	5.04527520902094	374.41800000000006
331	4.84771165561694	356.40300000000013
332	5.98296666070122	370.4300000000002
333	5.85387196432176	420.3840000000001
334	7.85387196432176	378.4250000000001
335	6.54515513999149	366.4140000000001
336	6.98716277529483	374.4620000000001
337	6.43297363384094	428.4320000000001
338	6.66354026615147	362.4510000000001
339	6.76195389687121	378.4250000000001
340	7.00877392430751	366.4140000000001
341	6.36151074304536	420.3840000000001
342	7.26760624017703	394.8800000000001
343	6.03857890593355	448.8500000000001
344	6.39040559077478	382.8690000000001
345	6.43651891460559	436.8390000000001
346	6.06550154875643	378.4250000000001
347	7.25963731050576	412.8700000000001
348	6.68613277963085	400.8590000000001
349	7.16115090926274	392.4520000000001
