id	property	mw	logp	hbd	hba	rotatable_bonds	tpsa	qed	stereocenters
0	6.0	447.5600000000001	4.926720000000004	0	5	8	76.30000000000001	0.3828946019708499	0
1	6.36999951009909	401.2600000000001	4.279520000000003	1	4	6	64.35000000000001	0.6698935916601484	0
2	6.90998897599285	405.2230000000001	4.110200000000002	1	4	6	64.35	0.6706688966306554	0
3	8.0100165416986	387.2330000000001	3.9711000000000025	1	4	6	64.35	0.6953407116014714	0
4	6.90000876645532	415.2870000000002	4.587940000000004	1	4	6	64.35000000000001	0.6399362216260406	0
5	6.9399824574684	435.70500000000015	4.932920000000003	1	4	6	64.35	0.595922996071404	0
6	7.83003182600311	437.2400000000001	4.557720000000002	1	4	6	64.35	0.6145472710517227	0
7	8.50003813440381	435.70500000000015	4.932920000000003	1	4	6	64.35	0.595922996071404	0
8	8.13000599987826	419.2500000000001	4.418620000000003	1	4	6	64.35	0.6428023974910582	0
9	8.05998184499234	435.70500000000015	4.932920000000004	1	4	6	64.35	0.595922996071404	0
10	9.2800061736324	437.2400000000001	4.557720000000002	1	4	6	64.35	0.6145472710517227	0
11	6.45000414846935	409.24400000000014	4.962920000000003	1	4	6	64.35	0.6250550207039217	0
12	8.55284196865778	322.372	1.0321999999999991	2	6	3	78.84	0.7529459253506232	0
13	6.07572071393812	441.45800000000014	2.3569	4	8	19	165.61	0.1327138660105428	3
14	6.08000196903598	441.45800000000014	2.3569	4	8	19	165.61	0.1327138660105428	3
15	5.85387196432176	354.48700000000014	3.475100000000002	3	4	13	94.83	0.3476126954257889	4
16	7.56863623584101	360.4940000000001	3.541300000000003	3	3	8	77.76	0.3514175873049406	6
17	5.27572413039921	367.4450000000001	4.237700000000003	1	4	8	68.12	0.5597185714745007	1
18	7.69897000433602	430.5040000000001	4.514500000000004	2	4	8	78.86999999999999	0.5141190764723529	1
19	5.61978875828839	415.4890000000001	4.724100000000004	1	4	8	68.12	0.4268259164633847	1
20	7.59998036493484	446.9380000000002	4.797220000000004	1	5	8	69.04	0.4219169939442359	0
21	6.90000876645532	397.9060000000001	4.610420000000004	1	4	7	56.150000000000006	0.632916780526133	0
22	7.0	369.8520000000001	3.831820000000002	1	4	6	56.150000000000006	0.7179782260679193	0
23	6.90000876645532	355.8250000000001	3.5711200000000023	1	4	6	70.14	0.7343950791333929	0
24	8.0	392.81800000000015	0.4007199999999999	0	5	6	67.17999999999999	0.5695306328279385	1
25	8.19997064075587	423.2420000000001	-0.0511800000000004	0	5	6	67.17999999999999	0.5219617942145582	0
26	8.0	378.7910000000001	-0.1602800000000008	0	5	6	67.17999999999999	0.5590279678870747	0
27	7.79997073344623	403.8410000000002	1.4713000000000005	0	4	6	62.25	0.5847157510257074	0
28	6.7999981345934	375.7870000000001	0.2722999999999993	0	4	6	62.25	0.5803236573221116	0
29	7.10001543745061	393.7770000000001	0.4113999999999995	0	4	6	62.25	0.5691879021924094	0
30	7.0	393.7770000000001	0.4113999999999995	0	4	6	62.25	0.5691879021924094	0
31	7.59998036493484	411.7670000000001	0.5504999999999998	0	4	6	62.25	0.555846514844188	0
32	7.10001543745061	429.7570000000001	0.6896	0	4	6	62.25	0.5410023135807661	0
33	7.4000078224159	410.23200000000014	0.9256999999999992	0	4	6	62.25	0.5677009467863644	0
34	7.4000078224159	410.23200000000014	0.9257	0	4	6	62.25	0.5677009467863644	0
35	7.89997426989214	428.22200000000015	1.0647999999999995	0	4	6	62.25	0.5515796078617662	0
36	7.89997426989214	428.22200000000015	1.0647999999999993	0	4	6	62.25	0.5515796078617662	0
37	8.0	444.6770000000002	1.5790999999999995	0	4	6	62.25	0.5417758069037505	0
38	7.4000078224159	341.7700000000001	-0.2719000000000002	0	4	6	62.25	0.6785385234569992	0
39	7.0	381.83500000000026	0.6523999999999994	0	4	6	62.25	0.689346949015692	0
40	7.50003813440381	367.8080000000002	0.2622999999999995	0	4	6	62.25	0.6872329214336562	0
41	6.69999179744619	339.75400000000013	-0.5179000000000002	0	4	6	62.25	0.6646343049733071	0
42	7.79588001734408	403.8410000000002	1.4713000000000005	0	4	6	62.25	0.5847157510257074	0
43	7.79997073344623	403.8410000000002	1.4713000000000005	0	4	6	62.25	0.5847157510257074	0
44	7.09691001300806	380.4410000000001	3.546720000000001	2	4	7	84.5	0.7693523445917434	0
45	7.88605664769316	396.4150000000001	3.5199000000000007	2	4	7	84.5	0.750043755629647	0
46	7.50863830616573	384.4040000000001	3.377400000000001	2	4	7	84.5	0.7665139152002287	0
47	5.25963731050576	295.408	1.3211999999999997	2	3	6	65.2	0.8445712183265353	0
48	8.39794000867204	432.48800000000017	2.686280000000001	0	10	6	117.09000000000002	0.5751536759926771	2
49	8.52287874528034	420.47700000000015	2.543780000000001	0	10	6	117.09000000000002	0.5885319349650595	1
50	7.92081875395238	406.45000000000016	2.1552800000000003	0	10	6	117.09000000000002	0.6024035544979289	0
51	8.09691001300806	448.4050000000001	2.6741800000000007	0	8	5	104.47	0.6877728264682342	2
52	7.50863830616573	436.3940000000001	2.5316800000000006	0	8	5	104.47	0.7043817985658688	1
53	7.74472749489669	422.3670000000001	2.14318	0	8	5	104.47	0.7219783113705146	0
54	9.0	422.48900000000015	2.910380000000001	0	8	4	104.47	0.7406811703181834	2
55	9.0	410.4780000000001	2.767880000000001	0	8	4	104.47	0.7577106951542149	1
56	8.0	396.45100000000014	2.3793800000000003	0	8	4	104.47	0.7757070641148665	0
57	6.45469288353418	448.5450000000002	2.5162000000000004	0	8	5	101.93	0.6876209789485163	0
58	4.73518217699046	320.331	3.256200000000001	2	6	3	81.13	0.6053897415537557	0
59	7.51999305704285	423.44800000000026	3.6705600000000023	0	7	5	104.17	0.7267303862640863	0
60	8.27083521030723	431.4750000000002	3.5384600000000024	0	8	6	103.65	0.5878994944001862	0
61	7.82390874094432	448.48700000000025	2.635480000000001	0	10	6	123.98	0.5636317874894765	0
62	7.95860731484178	415.4970000000002	3.499480000000003	0	7	6	84.04	0.6126828866281638	0
63	6.14026143380285	440.52500000000026	2.387220000000001	0	8	5	94.39	0.6011786944328358	0
64	6.73754891026957	448.5410000000002	3.019300000000001	0	7	4	94.91	0.7136059771233089	0
65	6.87614835903291	434.5140000000002	2.629200000000001	0	7	5	94.91	0.7180103239128796	0
66	5.96217524941166	448.5410000000002	3.019300000000001	0	7	5	94.91	0.6978546699380033	1
67	5.76955107862173	448.5410000000002	2.876800000000001	0	7	6	94.91	0.6744384992877699	0
68	6.47625353318844	400.5190000000002	4.664380000000005	0	5	4	71.78999999999999	0.7346760628405727	0
69	6.84163750790475	402.4950000000002	3.4543800000000022	0	7	4	97.57	0.7605221115053923	0
70	7.0329202658555	441.5500000000002	2.5961000000000007	0	8	6	107.92	0.6628200553459684	0
71	6.69897000433602	415.52700000000016	4.035300000000004	0	5	6	72.91	0.655960823925335	0
72	7.86774031046896	425.4110000000001	2.979000000000001	0	6	2	80.56	0.7391624686248698	0
73	8.14752000636314	414.49100000000016	2.5699000000000005	0	8	2	93.45	0.6398128846572791	0
74	8.37571790416433	400.41400000000016	1.97098	0	7	2	104.35	0.7633537426021078	0
75	8.50584540598156	435.5060000000002	1.3637	0	8	3	114.7	0.7149282590518661	0
76	7.98171569157347	440.4220000000001	3.842400000000003	0	7	3	86.55	0.6743828250401505	0
77	8.08777794346758	429.5020000000001	3.433300000000002	0	9	3	99.44	0.5881509279486715	0
78	8.44490555142168	415.4250000000001	2.834380000000001	0	8	3	110.34	0.7089446910937798	0
79	7.0	403.8410000000002	1.6154000000000004	0	4	7	62.25	0.4440144047708076	0
80	6.59999765407205	389.81400000000014	1.2253000000000005	0	4	6	62.25	0.5947879879834345	0
81	6.7999981345934	429.87900000000025	2.0054999999999987	0	4	6	62.25	0.5622676270454436	0
82	8.95860731484178	352.4710000000001	3.251100000000002	3	4	12	94.83	0.3701034711062733	4
83	8.29998893767789	332.7870000000001	4.461020000000003	1	4	4	68.25999999999999	0.7654099623000675	0
84	7.29998893767789	330.77100000000013	4.215020000000003	1	4	4	68.25999999999999	0.7774631623225688	0
85	7.59998036493484	332.78700000000003	4.290120000000004	1	4	5	68.26	0.7563610024792441	0
86	7.19997064075587	346.81400000000014	4.635120000000003	1	4	3	68.25999999999999	0.7499786860803379	0
87	6.59999765407205	332.7870000000001	4.461020000000003	1	4	4	68.25999999999999	0.7654099623000675	0
88	6.90000876645532	331.8030000000001	3.967520000000002	1	4	4	59.53	0.7866049260404545	0
89	6.29999760285775	332.7910000000001	3.3625200000000026	1	5	4	72.42	0.7947320144312509	0
90	7.19997064075587	415.9210000000001	4.671620000000003	1	5	5	69.28999999999999	0.6568666259454689	0
91	6.09999903484653	414.9370000000002	4.244620000000003	2	5	5	72.09	0.6543917267239939	0
92	7.0	414.9370000000002	4.893520000000004	1	5	5	63.3	0.6449065361513211	0
93	7.29998893767789	416.90900000000016	3.7398200000000026	1	6	5	72.53	0.6854941008482293	0
94	8.29998893767789	365.8200000000001	4.405320000000002	1	4	4	74.05000000000001	0.5818845865796068	0
95	6.30102999566398	361.426	4.575800000000003	1	5	4	68.01	0.5777885668621427	0
96	7.30102999566398	361.426	4.669420000000003	1	5	4	68.01	0.5734660367215905	0
97	7.07572071393812	353.325	4.021220000000001	1	5	3	68.01	0.7721421006511971	0
98	6.74472749489669	355.297	3.4184	2	6	3	88.24	0.7515654105391998	0
99	6.23657200643706	355.297	3.4184	2	6	3	88.24	0.7515654105391998	0
100	6.49485002168009	355.297	3.4184	2	6	3	88.24	0.7515654105391998	0
101	5.52287874528034	353.325	4.021220000000001	1	5	3	68.01	0.7721421006511971	0
102	6.49485002168009	339.29800000000006	3.712800000000001	1	5	3	68.00999999999999	0.7897157180354136	0
103	6.36653154442041	369.324	3.721400000000002	1	6	4	77.24000000000001	0.758427164963217	0
104	6.0	369.324	3.721400000000002	1	6	4	77.24	0.758427164963217	0
105	8.69897000433602	373.4370000000002	4.459600000000003	1	5	3	68.00999999999999	0.5756569879926153	0
106	7.69897000433602	361.3820000000001	4.593400000000003	1	6	3	81.14999999999999	0.5080663934797792	0
107	9.04575749056068	359.41000000000014	4.265200000000003	1	5	3	68.00999999999999	0.5224080053464609	0
108	7.69897000433602	362.414	3.943200000000002	2	6	4	94.03	0.5732894355077114	0
109	7.22184874961636	363.3980000000001	4.066600000000002	2	6	4	88.24	0.5705975398483715	0
110	7.52287874528034	365.3890000000001	4.500100000000002	1	5	4	68.00999999999999	0.5781122289640273	0
111	6.48148606012211	375.4530000000001	4.977840000000004	1	5	4	68.01	0.5462575752412181	0
112	7.0	379.41600000000005	4.808520000000002	1	5	4	68.01	0.5525492485153646	0
113	7.30102999566398	379.41600000000005	4.808520000000002	1	5	4	68.01	0.5525492485153646	0
114	7.09691001300806	367.455	4.730920000000002	1	6	4	68.01	0.5660434142426575	0
115	6.92081875395238	367.455	4.730920000000002	1	6	4	68.01	0.5660434142426575	0
116	7.30102999566398	361.426	4.669420000000003	1	5	4	68.01	0.5734660367215905	0
117	7.49485002168009	342.4240000000001	3.416500000000002	1	6	3	71.25	0.7895628988126518	0
118	7.79588001734408	328.397	3.170500000000001	1	6	3	71.25	0.7993981580558449	0
119	7.52287874528034	327.39000000000004	3.9087000000000014	1	6	3	68.00999999999999	0.619301503006245	0
120	8.39794000867204	325.393	4.137600000000003	1	5	3	68.00999999999999	0.7856695603577244	0
121	7.09691001300806	311.366	3.7475000000000014	1	5	3	68.00999999999999	0.7996414351037965	0
122	6.85387196432176	389.35800000000006	4.866000000000002	1	5	3	68.00999999999999	0.543049087957267	0
123	8.39794000867204	351.38700000000006	3.855800000000002	1	6	4	77.24	0.6040704351239429	0
124	7.92081875395238	355.8060000000001	4.500600000000002	1	5	3	68.00999999999999	0.5871247047001972	0
125	7.69897000433602	339.35100000000006	3.9863000000000017	1	5	3	68.00999999999999	0.6127679183921527	0
126	8.34678748622466	339.35100000000006	3.9863000000000026	1	5	3	68.00999999999999	0.6127679183921527	0
127	9.22184874961636	389.35800000000006	4.866000000000001	1	5	3	68.00999999999999	0.5430490879572671	0
128	7.30102999566398	350.4030000000001	3.888900000000002	2	6	4	80.04	0.5835864678570437	0
129	7.72124639904717	336.37600000000003	3.429400000000001	2	6	3	94.03	0.559018942853224	0
130	7.0	365.4140000000001	4.245900000000002	1	6	5	77.24	0.5721237070807116	0
131	8.95860731484178	351.38700000000006	3.855800000000002	1	6	4	77.24	0.6040704351239429	0
132	6.85387196432176	337.36000000000007	3.5528000000000013	2	6	3	88.24	0.5966803476947825	0
133	9.0	335.38800000000003	4.1556200000000025	1	5	3	68.01	0.6103766961262165	0
134	8.69897000433602	339.35100000000006	3.9863000000000017	1	5	3	68.00999999999999	0.6127679183921527	0
135	7.09691001300806	339.35100000000006	3.9863000000000017	1	5	3	68.00999999999999	0.6127679183921527	0
136	6.30102999566398	339.35100000000006	3.9863000000000017	1	5	3	68.00999999999999	0.6127679183921527	0
137	7.4089353929735	322.34900000000005	3.2422000000000013	1	6	3	80.89999999999999	0.6260260392644649	0
138	6.69897000433602	322.34900000000005	3.2422000000000013	1	6	3	80.89999999999999	0.6260260392644649	0
139	6.0	339.42000000000024	3.962900000000003	1	5	3	68.00999999999999	0.733403566279071	0
140	7.79588001734408	325.3930000000002	3.5728000000000018	1	5	3	68.00999999999999	0.7990904846625129	0
141	6.92081875395238	320.37300000000005	4.452200000000002	1	4	3	55.12	0.6064450278887044	0
142	8.61978875828839	321.36100000000005	3.8472000000000017	1	5	3	68.00999999999999	0.6221782585439329	0
143	5.70000050388302	325.459	1.3947	1	4	4	66.64	0.9237254099496348	0
144	6.59999765407205	350.488	1.7006	2	3	5	68.44	0.862377141000895	0
145	6.90000876645532	336.461	0.9645000000000008	2	3	6	68.44	0.8256992977763365	0
146	6.19999817218203	322.434	1.2686	1	3	4	59.650000000000006	0.922036405954912	0
147	6.0	350.488	1.7006	2	3	5	68.44	0.862377141000895	0
148	6.90000876645532	350.48800000000006	1.6543	1	3	5	59.650000000000006	0.8920348164120309	0
149	6.51712641639125	368.5210000000001	4.421300000000002	2	3	10	64.35	0.652283757757385	3
150	6.70996538863748	369.50500000000005	4.454900000000004	2	3	10	58.56	0.6501821270737915	3
151	5.74957999769111	310.427	2.213	3	7	9	99.61	0.3707563358573986	1
152	6.43889861635094	428.5660000000001	3.842000000000004	4	5	13	97.99	0.2814859017627914	5
153	5.30102999566398	393.52400000000006	3.0227000000000017	5	5	13	110.02	0.3296071094959475	5
154	6.3045183235098	424.92100000000016	3.195000000000002	4	5	11	107.22	0.320780398275472	5
155	5.2518119729938	392.53600000000006	3.543400000000003	4	4	13	97.99	0.384986243887741	5
156	6.04000516167158	410.5760000000001	3.7029000000000023	4	5	13	97.99	0.2923546963028123	5
157	5.95860731484178	416.6050000000001	3.7644000000000033	4	6	13	97.99	0.2886578458760542	5
158	6.14691047014813	394.508	2.9896000000000016	4	5	13	107.22	0.3832524337504368	5
159	5.86646109162978	428.9530000000001	3.643000000000003	4	5	13	107.22	0.35714726181743	5
160	5.33724216831843	424.6030000000002	4.011320000000002	4	5	13	97.99	0.2820981845161118	5
161	6.42021640338319	354.487	3.042900000000001	4	4	12	97.99	0.3189173783556326	5
162	6.65757731917779	354.487	3.042900000000001	4	4	12	97.99	0.3189173783556326	5
163	5.95860731484178	392.53600000000006	3.543400000000003	4	4	13	97.99	0.384986243887741	5
164	5.0	410.52600000000007	3.682500000000003	4	4	13	97.99	0.3719860937219846	5
165	5.46218090492673	410.52600000000007	3.682500000000003	4	4	13	97.99	0.3719860937219846	5
166	5.50863830616573	410.52600000000007	3.682500000000003	4	4	13	97.99	0.3719860937219846	5
167	5.0	406.5630000000002	3.851820000000002	4	4	13	97.99	0.3730786914406689	5
168	8.18996921359416	401.2600000000001	4.279520000000003	1	4	6	64.35	0.6698935916601484	0
169	6.17000191130262	417.2590000000002	3.4634000000000023	2	5	7	84.58	0.615302495097338	0
170	6.09999903484653	322.434	0.9220000000000006	2	3	5	68.44	0.8600916854930767	0
171	6.19999817218203	308.407	0.6613000000000001	2	3	4	82.43	0.8703205411119768	0
172	6.90000876645532	364.51500000000016	1.6968	1	3	7	59.65	0.8134312098760719	0
173	6.09999903484653	336.461	1.2642000000000004	1	3	5	59.650000000000006	0.894298485409071	0
174	6.09999903484653	322.434	0.9220000000000006	2	3	5	68.44	0.8600916854930767	0
175	6.69999179744619	350.48800000000006	1.3067000000000004	1	3	6	59.650000000000006	0.854434120469873	0
176	7.10001543745061	398.532	2.8390000000000013	1	3	6	59.650000000000006	0.6946237328077031	0
177	6.29999760285775	364.51500000000016	2.0428000000000006	1	3	6	59.65	0.8533186836749389	0
178	6.29999760285775	295.408	1.3211999999999997	2	3	6	65.2	0.8445712183265353	0
179	7.10237290870956	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
180	6.74472749489669	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
181	6.73518217699046	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
182	6.55284196865778	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
183	6.79588001734408	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
184	6.74472749489669	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
185	6.74472749489669	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
186	6.58502665202918	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
187	0.340000000004633	317.8200000000001	2.8462000000000014	1	3	4	45.23	0.9428403735855508	1
188	0.309999999998622	329.8310000000002	2.988700000000001	1	3	5	45.23	0.9168830308247438	1
189	0.329999999997398	290.794	3.4044000000000016	1	3	5	34.15	0.8571106492371322	1
190	0.290000000001156	338.86000000000007	2.802600000000001	1	4	4	59.06	0.9308903670918596	1
191	0.340000000004633	326.831	3.4369000000000023	1	4	4	42.74	0.7983593079907493	1
192	0.320000000002395	297.78900000000004	3.6155000000000017	1	3	5	37.81	0.7310598326845887	0
193	0.320000000002395	327.83700000000005	1.8692000000000009	1	4	6	62.3	0.8227452818249423	0
194	0.320000000002395	290.3880000000001	1.7590999999999997	1	4	4	59.06	0.9318988549108204	1
195	0.329999999997398	304.4150000000001	2.1492	1	4	4	59.06	0.9400512534538416	1
196	0.299999999997636	353.8750000000001	2.4018000000000006	1	4	6	62.3	0.8658164586440914	0
197	0.320000000002395	293.39200000000005	1.2157999999999998	1	4	6	62.3	0.813437111843331	0
198	0.290000000001156	311.382	1.3549000000000004	1	4	6	62.3	0.8182603760679634	0
199	0.320000000002395	290.38800000000015	1.9016	1	4	5	59.06	0.9134828629250492	0
200	0.290000000001156	369.28400000000016	2.664100000000001	1	4	5	59.06	0.8805482133843403	0
201	0.279999999999811	324.83300000000014	2.5550000000000006	1	4	5	59.06	0.9179525376759304	0
202	5.47886191629596	306.3582035560001	1.9838	3	3	5	93.62999999999998	0.7344534379191102	0
203	5.47886191629596	304.34600000000006	1.9838	3	3	5	93.63	0.7344266475903526	0
204	6.58502665202918	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
205	6.58502665202918	176.21899999999997	1.3747	3	2	2	62.040000000000006	0.6468452624532928	0
206	7.50003813440381	433.5040000000001	4.669300000000003	2	5	7	79.23	0.5638052304300277	0
207	7.61978875828839	429.5860000000001	3.5643400000000023	2	4	6	78.51	0.7359261462575689	1
208	7.07058107428571	437.56500000000017	3.676820000000002	3	4	6	87.3	0.54906007682013	2
209	7.88605664769316	443.61300000000017	3.8183200000000026	2	4	7	78.51	0.6819483884789563	1
210	7.48148606012211	440.5690000000002	3.127600000000002	2	5	6	102.29999999999998	0.7184865791929932	1
211	8.22184874961636	447.57600000000014	3.7034400000000014	2	4	6	78.51	0.7077987556584545	1
212	8.39794000867204	443.61300000000017	3.872760000000003	2	4	6	78.51	0.7103665081784564	1
213	6.13371266091581	431.5580000000002	2.922320000000001	3	5	7	96.53	0.6264059152837005	1
214	7.55284196865778	435.6340000000003	3.9125200000000016	2	4	6	78.51	0.6641980030782931	1
215	7.48148606012211	435.6150000000001	3.625840000000002	2	5	6	78.51	0.7263355425705952	1
216	6.60032627851896	415.5590000000001	3.175840000000001	2	4	6	78.51	0.7595933423002776	0
217	7.47108329972235	429.5860000000001	3.5643400000000023	2	4	6	78.51	0.7359261462575689	1
218	6.85387196432176	183.276	1.5813	1	3	2	21.26	0.7513592840174587	1
219	6.09999903484653	355.77700000000004	4.804500000000003	1	4	6	68.65	0.6871302339169445	0
220	7.29998893767789	381.8160000000001	0.3388999999999991	0	5	6	62.25	0.5776312598653021	0
221	6.19999817218203	367.789	0.4099999999999995	0	5	5	62.25	0.6128089396681782	0
222	7.59998036493484	382.8040000000001	0.486599999999999	1	6	6	74.28	0.627920951532907	0
223	7.4000078224159	319.78800000000007	4.058800000000002	1	3	6	59.42	0.8719395726507299	0
224	8.50003813440381	330.74300000000005	-0.0739000000000009	0	4	6	62.5	0.6954670187571353	0
225	8.10001543745061	347.79900000000004	-0.2104000000000001	0	5	6	62.25	0.6783988495378327	0
226	8.0	344.7740000000001	-0.7044799999999991	0	5	6	67.17999999999999	0.6496991542222271	0
227	6.19999817218203	375.7870000000001	0.2722999999999997	0	4	6	62.25	0.5803236573221116	0
228	6.7999981345934	353.80500000000006	4.603000000000003	1	3	6	59.42	0.703007945803386	0
229	6.49999693194831	374.7990000000001	0.8772999999999993	0	3	6	49.36	0.6017737983890179	0
230	7.4000078224159	380.8280000000001	0.9387999999999996	0	4	6	49.36	0.5979738932215545	0
231	7.29998893767789	380.828	0.9387999999999996	0	4	6	49.36	0.5979738932215545	0
232	8.0	378.7870000000001	0.7787199999999994	0	4	6	62.5	0.5946529714520444	0
233	8.19997064075587	364.7600000000001	0.4702999999999997	0	4	6	62.5	0.5965549597701845	0
234	6.49999693194831	393.27000000000015	4.363300000000003	1	4	6	64.35000000000001	0.6759206087640022	0
235	6.19999817218203	381.816	0.3337999999999999	0	5	6	62.25	0.5774414828839054	0
236	7.59998036493484	381.816	0.3337999999999999	0	5	6	62.25	0.5774414828839054	0
237	7.70005709997723	365.7480000000001	-0.1347000000000002	0	5	6	75.39	0.5686237976043139	0
238	8.19997064075587	381.8160000000001	0.3337999999999994	0	5	6	62.25	0.5774414828839053	0
239	6.7999981345934	355.8210000000001	4.775420000000003	1	3	6	51.46	0.6921742455436063	0
240	7.10001543745061	364.764	-0.4687000000000003	0	5	6	67.17999999999999	0.5547202270346303	0
241	8.0	378.7910000000001	-0.1602800000000008	0	5	6	67.17999999999999	0.5590279678870747	0
242	8.19997064075587	401.2600000000001	4.279520000000003	1	4	6	64.35	0.6698935916601484	0
243	8.19997064075587	356.81	0.3063999999999995	0	5	4	57.95	0.6320431458110445	0
244	8.20065945054642	356.81	0.3063999999999995	0	5	4	57.95	0.6320431458110445	0
245	8.19997064075587	423.2420000000001	-0.0511800000000004	0	5	6	67.17999999999999	0.5219617942145582	0
246	7.4000078224159	341.7700000000001	-0.2719000000000002	0	4	6	62.25	0.6785385234569992	0
247	6.7999981345934	375.7870000000001	0.2722999999999993	0	4	6	62.25	0.5803236573221116	0
248	7.59998036493484	382.8040000000001	0.486599999999999	1	6	6	74.28	0.627920951532907	0
249	8.10001543745061	347.79900000000004	-0.2104000000000001	0	5	6	62.25	0.6783988495378327	0
250	8.19997064075587	381.8160000000001	0.3337999999999994	0	5	6	62.25	0.5774414828839053	0
251	6.7999981345934	390.8270000000001	0.6986999999999997	0	5	4	57.95	0.4819342747966604	0
252	7.4000078224159	342.7830000000001	0.2313	0	5	3	57.95	0.6403399215333618	0
253	7.4000078224159	370.8370000000001	0.6148199999999995	0	5	4	57.95	0.6324077484221615	0
254	7.4000078224159	356.81	0.3063999999999995	0	5	4	57.95	0.6320431458110445	0
255	6.19999817218203	349.79300000000006	0.8498999999999997	0	3	4	45.06	0.6555374404400566	0
256	7.19997064075587	350.781	0.2448999999999999	0	4	4	57.95	0.6335995412588369	0
257	8.19997064075587	370.8370000000001	0.3654999999999999	0	5	5	57.95	0.6095249425504803	0
258	6.7999981345934	370.8370000000001	0.2353	0	5	5	57.95	0.6043201640139858	0
259	7.29998893767789	355.82200000000006	0.9113999999999998	0	4	4	45.06	0.6530560612200181	0
260	7.59998036493484	339.754	0.4428999999999996	0	4	4	58.2	0.6482496297098874	0
261	7.0	356.81	0.3064	0	5	4	57.95	0.6320431458110445	0
262	8.10001543745061	340.742	-0.1621000000000001	0	5	4	71.09	0.618703292098831	0
263	8.0	336.39200000000005	-0.0385800000000005	0	5	4	57.95	0.6284854297216474	0
264	7.89997426989214	390.362	0.6717999999999997	0	5	4	57.95	0.6157652983677669	0
265	8.4000078224159	401.261	0.4154999999999997	0	5	4	57.95	0.5957971364973504	0
266	7.4000078224159	340.355	-0.2078999999999999	0	5	4	57.95	0.617903216731638	0
267	6.7999981345934	322.365	-0.347	0	5	4	57.95	0.61728671555509	0
268	6.0	371.781	-1.1902999999999997	0	6	3	78.26	0.5423835724078772	0
269	7.0	370.79300000000006	-0.0534000000000003	0	6	4	75.02	0.4763847906390971	0
270	6.59999765407205	382.726	0.2127000000000001	0	5	3	57.95	0.608688054404001	0
271	6.90000876645532	328.75600000000003	-0.3297000000000003	0	5	3	57.95	0.6187212288612477	0
272	7.50003813440381	342.7830000000001	0.0603999999999995	0	5	4	57.95	0.6300581577045227	0
273	8.19997064075587	384.8640000000001	1.0865999999999998	0	5	4	57.95	0.6325556654220816	0
274	7.50003813440381	370.8370000000001	0.6964999999999999	0	5	3	57.95	0.6375612517735891	0
275	6.39999691337226	432.9110000000001	4.740000000000004	1	5	8	69.04	0.4363190033721395	0
276	7.19997064075587	421.9250000000001	4.6555200000000045	1	6	7	74.61	0.7034870621516739	0
277	7.29998893767789	379.88800000000015	4.884920000000004	1	5	7	65.38	0.7436831388759556	0
278	7.10001543745061	441.9150000000001	4.809620000000004	1	6	7	74.61	0.5691230579523245	1
279	6.69999179744619	385.8510000000001	4.650520000000004	1	5	6	65.38	0.6702914037836419	0
280	7.19997064075587	439.9430000000001	4.8373200000000045	1	5	7	65.38	0.5718264460848014	0
281	7.4000078224159	425.9160000000001	4.447220000000003	1	5	7	65.38	0.6070663828371736	1
282	7.4000078224159	425.9160000000001	4.589720000000004	1	5	7	65.38	0.6008784908409811	1
283	6.49999693194831	369.8520000000001	4.430620000000003	1	4	6	56.150000000000006	0.6988343763190307	0
284	6.59999765407205	406.91400000000016	2.9050200000000013	1	6	7	68.62	0.7652327757862245	0
285	6.69999179744619	404.9420000000002	4.058720000000003	1	5	7	59.39	0.7555338141021135	0
286	6.90000876645532	321.8080000000001	3.0269200000000014	1	4	6	70.14	0.8886491254058466	0
287	7.10001543745061	446.9380000000002	4.797220000000004	1	5	8	69.04	0.4219169939442359	0
288	7.29998893767789	446.9380000000002	4.797220000000004	1	5	8	69.04	0.4219169939442359	0
289	5.11350927482752	376.4120000000001	3.0863000000000014	2	4	8	88.52000000000001	0.6306962355886782	1
290	8.43179827593301	445.3500000000002	4.277120000000003	2	5	5	66.49	0.614072779614996	0
291	8.16749108729376	447.3660000000001	4.523120000000003	2	5	8	66.49	0.5316302691630153	0
292	8.06048074738138	448.3500000000002	4.807920000000005	1	5	8	63.69	0.5361620960413679	0
293	8.19382002601611	445.44100000000014	4.522220000000004	2	5	7	74.69000000000001	0.5232898262385866	0
294	6.29242982390206	361.4450000000001	4.170370000000002	3	4	8	80.36	0.415447608157827	0
295	5.48148606012211	361.4450000000001	4.170370000000002	3	4	8	80.36	0.415447608157827	0
296	5.2839966563652	362.4330000000001	3.565370000000001	3	5	8	93.25	0.4207223667991503	0
297	6.53760200210104	367.4740000000001	4.231870000000002	3	5	8	80.36	0.4110217443322332	0
298	6.16749108729376	426.52000000000015	4.961070000000003	3	5	9	85.28999999999999	0.2607998822115968	0
299	5.72124639904717	341.4550000000001	4.016270000000003	3	4	9	80.36	0.4752928949036139	0
300	5.2839966563652	331.419	4.161770000000003	3	3	7	71.13000000000001	0.4495070358188169	0
301	6.03621217265444	361.467	3.613190000000001	3	4	8	105.27	0.4931184073139759	0
302	6.52287874528034	347.44000000000005	3.3047700000000004	3	4	8	105.27	0.5030129859821624	0
303	5.65757731917779	361.467	3.613190000000001	3	4	8	105.27	0.4931184073139759	0
304	6.79588001734408	395.4840000000001	4.180610000000002	3	4	6	105.27	0.429926684164373	0
305	5.67778070526608	399.4470000000001	4.011290000000002	3	4	6	105.27	0.4300707439688893	0
306	7.0	411.4830000000001	3.880790000000002	3	5	7	114.5	0.4031305106464146	0
307	5.44369749923271	411.4830000000001	3.880790000000001	3	5	7	114.5	0.4031305106464146	0
308	4.63827216398241	411.4830000000001	3.880790000000001	3	5	7	114.5	0.4031305106464146	0
309	7.30102999566398	435.50500000000017	4.727120000000003	2	6	6	103.54	0.4538852605150597	0
310	6.31875876262441	270.357	4.408860000000002	0	4	2	35.010000000000005	0.691566244177945	0
311	4.83863199776503	242.303	3.7920200000000017	0	4	2	35.010000000000005	0.6853730756453904	0
312	5.79588001734408	256.33	4.1004400000000025	0	4	2	35.010000000000005	0.6920313654056011	0
313	4.60205999132796	270.357	4.408860000000002	0	4	2	35.010000000000005	0.6915662441779451	0
314	5.56863623584101	270.357	4.408860000000002	0	4	2	35.010000000000005	0.691566244177945	0
315	6.65757731917779	274.32000000000005	4.239540000000002	0	4	2	35.010000000000005	0.7007561594842571	0
316	4.52287874528034	274.32000000000005	4.2395400000000025	0	4	2	35.010000000000005	0.7007561594842571	0
317	5.95860731484178	274.32000000000005	4.2395400000000025	0	4	2	35.010000000000005	0.7007561594842571	0
318	5.3767507096021	246.266	3.622700000000001	0	4	2	35.010000000000005	0.6922768767156846	0
319	5.76955107862173	260.293	3.9311200000000017	0	4	2	35.010000000000005	0.6998617196050372	0
320	5.82390874094432	260.293	3.931120000000001	0	4	2	35.010000000000005	0.6998617196050372	0
321	5.67778070526608	314.263	4.641500000000001	0	4	2	35.010000000000005	0.6462857100545195	0
322	6.49485002168009	302.374	4.920200000000003	0	4	2	35.010000000000005	0.6736411855639984	0
323	6.90657831483776	360.4350000000001	3.2417000000000016	2	4	7	84.5	0.7937615203515412	0
324	5.54821356447571	374.4620000000001	3.630200000000002	2	4	7	84.5	0.7749873415773536	0
325	5.50307035192679	400.50000000000006	4.164400000000002	2	4	7	84.5	0.7306970917222791	0
326	6.2958494831602	374.4620000000001	3.631800000000002	2	4	8	84.5	0.7388524113012936	0
327	6.29929628285498	414.4050000000001	3.784100000000002	2	4	7	84.5	0.7222043640218141	0
328	5.86646109162978	386.47300000000007	3.631800000000002	2	4	8	84.5	0.7254989042602343	0
329	5.96257350205938	404.4880000000003	3.6404000000000014	2	5	9	93.73	0.6654762826711783	0
330	5.04527520902094	374.41800000000006	2.614200000000001	2	5	5	93.73	0.8390561780384884	0
331	4.84771165561694	356.40300000000013	3.5892000000000017	2	4	5	88.41	0.7310983834738377	0
332	5.98296666070122	370.4300000000002	3.8976200000000016	2	4	5	88.41000000000001	0.7128779345127583	0
333	5.85387196432176	420.3840000000001	3.780700000000002	2	4	7	84.5	0.668043139473442	0
334	7.85387196432176	378.4250000000001	3.3808000000000007	2	4	7	84.5	0.7735361687077846	0
335	6.54515513999149	366.4140000000001	3.2383000000000006	2	4	7	84.5	0.7878207620431864	0
336	6.98716277529483	374.4620000000001	3.5501200000000024	2	4	7	84.5	0.7761354406831596	0
337	6.43297363384094	428.4320000000001	4.092520000000002	2	4	7	84.5	0.6957505494778136	0
338	6.66354026615147	362.4510000000001	3.407620000000001	2	4	7	84.5	0.7904223636322304	0
339	6.76195389687121	378.4250000000001	3.3808000000000016	2	4	7	84.5	0.7735361687077846	0
340	7.00877392430751	366.4140000000001	3.238300000000001	2	4	7	84.5	0.7878207620431864	0
341	6.36151074304536	420.3840000000001	3.780700000000002	2	4	7	84.5	0.668043139473442	0
342	7.26760624017703	394.8800000000001	3.895100000000002	2	4	7	84.5	0.7455041087323312	0
343	6.03857890593355	448.8500000000001	4.437500000000003	2	4	7	84.5	0.6555927054060973	0
344	6.39040559077478	382.8690000000001	3.752600000000002	2	4	7	84.5	0.7632282161706335	0
345	6.43651891460559	436.8390000000001	4.295000000000003	2	4	7	84.5	0.6775591064481713	0
346	6.06550154875643	378.4250000000001	3.3808000000000016	2	4	7	84.5	0.7735361687077846	0
347	7.25963731050576	412.8700000000001	4.034200000000002	2	4	7	84.5	0.7184892839055332	0
348	6.68613277963085	400.8590000000001	3.891700000000002	2	4	7	84.5	0.7379299599714483	0
349	7.16115090926274	392.4520000000001	3.6892200000000015	2	4	7	84.5	0.7526528481706041	0
