task: workflow
workflow_name: protein_modelling

workflow:
  - fix_residues
  - fix_loops
  - cap_terminals
  - refine_loops

protein:
  pdb_path: "/home/corey/Documents/the_kitbag/pipelines/structure_modelling/projects/test/5yhl.pdb"
  uniprot_id: P35408
  allow_missing_atoms_fix: true

  capping:
    enabled: true
    n_term: ACE
    c_term: NME

backend:
  name: pyrosetta
  rosetta_args: "-mute all"
  n_loop_models: 20
  loop_closure: "KIC"  # KIC | CCD | hybrid | auto
  loop_refinement:
    enabled: true
    relax_after_loop: true
    local_minimize_radius: 5.0
    global_relax_cycles: 2
    score_function: "ref2015"

output_dir: "outputs/loop_modelling"
