task: workflow
workflow_name: peptide_modelling

workflow:
  - build_peptide
  - generate_peptide_conformers
  # - optimise_peptide_conformers
  - analyse_peptide_flexibility
  - plot_peptide_flexibility

backend:
  name: peptidebuilder

build_peptide:
  sequence_file: "data/peptides.txt"
  cap_termini: true

generate_peptide_conformers:
  number_of_conformers: 100 # 50 - 100 should sample enough conformers

output_dir: "outputs/peptide_modelling"
cleanup: true