task: workflow
workflow_name: peptide_modelling

workflow:
  - build_peptide
  - minimise_peptide

backend:
  name: build_peptide         # or colabfold

peptide:
  sequence_file: "data/peptides.txt"

minimization:
  engine: openmm
  method: steepest_descent
  steps: 5000
  platform: cpu
  forcefield: amber14-all.xml
  implicit_solvent: true

output_dir: "outputs/peptide_modelling"