# Generating a focused library from database fragments.

# Purpose: to generate separate libraries of compounds from a dataset based on scaffold.
# Workflow: take a library of compounds with known bioactivities, filter actives, 
# fragmentby BRICS/MACCS/etc. to find scaffolds, create separate libraries containing these scaffolds.  
# Outputs: SDFs by scaffold membership for docking or other post-processing.

workflow_name: dynamic_task_runner

input_file: data/class_a_gpcr_bioactivity_small.csv
chunk_size: 1000

workflow:
  - activity_filtering
  - focused_fragment_library_generator

activity:
  value_cutoff_nM: 1000

focused_fragment_library:
  fragment_type: BRICS  # or MACCS or RECAP or MURCKO
  frequency_threshold: 0.3 # set higher to limit matches if you get too many
  max_fragments: 100  # Optional limit on number of fragments to keep
  group_by_target: true  # Optional: group by target or analyze across all
  output_fragments: true
  output_sdf_per_fragment: true

output:
  directory: outputs/focused_library
  filename: class_a_gpcr_focused_library.csv
  overwrite: true

cleanup: true
