workflow_name: dynamic_task_runner

input_file: data/class_a_gpcr_bioactivity_with_date_test.csv
chunk_size: 100

workflow_parallel:
  - basic_lipinski_filtering
  - physchem_filtering
workflow_serial:
  - mmp_analysis
  - mmp_report

basic_lipinski:
  mw_cutoff: 450
  hbd_cutoff: 5
  hba_cutoff: 10
  rotatable_bonds_cutoff: 10
physchem:
  logp_cutoff: 4.5
  tpsa_cutoff: 140
  qed_cutoff: 0.4
  stereocenters_cutoff: 2
mmp_report:
  min_count: 10
  significance_level: 0.05

output:
  directory: outputs/mmp
  filename: class_a_gpcr_physchem_tox_filtered_mmp.csv
  overwrite: true

cleanup: true  # deletes intermediate steps after success
