# GPCR Pocket Classification

# Purpose: To classify GPCR pockets (from fpocket) into known, orphan, and non-functional categories.
# Workflow:
# - feed in
#   - pocket data (from fpocket), including pocket names and their SMILES
#   - 7TM and ECD regions predicted via DeepTMHMM or manually defined
# - output: CSV with classified pockets, their locations (7TM/ECD), and functional classifications

workflow_name: dynamic_task_runner

workflow_serial:
  - run_fpocket
  - pocket_classification


run_fpocket:
  structure_directory: data/pdbs
  output_directory: outputs/fpocket_output
  # max_pockets_per_structure: 100

output:
  directory: outputs/gpcr_pocket_classification
  filename: classified_gpcr_pockets.csv
  overwrite: true

cleanup: true
