workflow_name: run_pipeline

workflow:
  # - load_building_blocks
  # - process_building_blocks
  # - save_building_block_database
  - validate_building_block_database
  - plot_building_block_database
  - classify_building_blocks
  - annotate_building_block_reactivity
  - validate_reactivity_annotations
  - build_building_block_search_index


load_building_blocks:
  input_file: input/mcule_purchasable_building_blocks_260802.smi
  smiles_col: smiles
  id_col: mcule_id


process_building_blocks:
  canonicalise_smiles: true
  remove_invalid_smiles: true
  remove_duplicates: true

  descriptors:
    - molecular_weight
    - logp
    - tpsa
    - hbd
    - hba
    - rotatable_bonds
    - ring_count
    - heavy_atom_count

  parallel:
    enabled: true
    n_workers: 16
    chunk_size: 10000

save_building_block_database:
  output_file: outputs/commercial_bbs/mcule_building_blocks.parquet

validate_building_block_database:
  input_file: outputs/commercial_bbs/mcule_building_blocks.parquet
  output_file: outputs/commercial_bbs/validation/validation_summary.json

  very_small_mw: 50
  very_large_mw: 800


plot_building_block_database:
  input_file: outputs/commercial_bbs/mcule_building_blocks.parquet
  output_dir: outputs/commercial_bbs/validation

  very_small_mw: 50
  very_large_mw: 800

  mw_normal_min: 50
  mw_normal_max: 800

  logp_normal_min: -5
  logp_normal_max: 10

  tpsa_normal_min: 0
  tpsa_normal_max: 250

  hac_normal_min: 3
  hac_normal_max: 60

  mw_plot_max: 1000
  max_molecules_per_category: 25


classify_building_blocks:
  input_file: outputs/commercial_bbs/mcule_building_blocks.parquet

  retrosynthesis_output: outputs/commercial_bbs/mcule_retrosynthesis_building_blocks.parquet
  excluded_output: outputs/commercial_bbs/mcule_excluded_building_blocks.parquet

  very_small_mw: 50
  very_large_mw: 800

  min_heavy_atoms: 3
  max_heavy_atoms: 60

  allowed_elements:
    - H
    - B
    - C
    - N
    - O
    - F
    - P
    - S
    - Cl
    - Br
    - I
    - Si
  
annotate_building_block_reactivity:
  input_file: outputs/commercial_bbs/mcule_retrosynthesis_building_blocks.parquet

  output_file: outputs/commercial_bbs/mcule_retrosynthesis_building_blocks_reactivity.parquet

  parallel:
    enabled: true
    n_workers: 16
    chunk_size: 10000

validate_reactivity_annotations:
  input_file: outputs/commercial_bbs/mcule_retrosynthesis_building_blocks_reactivity.parquet

  output_dir: outputs/commercial_bbs/validation/reactivity

  sample_size: 25
  random_state: 42

build_building_block_search_index:
  input_file: outputs/commercial_bbs/mcule_retrosynthesis_building_blocks_reactivity.parquet

  output_dir: outputs/commercial_bbs/search_index