workflow_name: train_model

workflow:
  - load_smiles_dataset
  - filter_druglike
  - transform_labels
  - featurise_smiles
  - split_data
  - load_adme_model_spec
  - train_adme_model
  - evaluate_adme_model

load_smiles_dataset:
  # csv_path: inputs/chembl_mtl_dataset.csv
  csv_path: inputs/2026-04-15_chembl_mtl_dataset_1k.csv
  ### options for sampling, if you need them
  # sampling: 
  #   sample_type: balanced | quantil
  #   n_bins: 20
  #   max_samples_per_bin: 500
    # plot_distributions: true
    # plot_dir: outputs/cyp3a4/sampling

transform_labels:
  label_cols:
    - Solubility
    - LogP
    - LogD
    - Caco-2_AB_mean
    - Microsomal Stability_Human_mean
    - CYP3A4_IC50_mean
    - CYP2D6_IC50_mean
    - CYP2C9_IC50_mean
    - CYP1A2_IC50_mean
    - hERG_IC50_mean
  outlier_bounds:
    LogP: [-5, 10]
    LogD: [-5, 10]
    
featurise_smiles:
  featuriser:
    module: models.adme.mtl_adme.featurisation
    function: mol_to_graph
  smiles_col: smiles
  label_cols:
    - Solubility
    - LogP
    - LogD
    - Caco-2_AB_mean
    - Microsomal Stability_Human_mean
    - CYP3A4_IC50_mean
    - CYP2D6_IC50_mean
    - CYP2C9_IC50_mean
    - CYP1A2_IC50_mean
    - hERG_IC50_mean

split_data:
  val_size: 0.2
  batch_size: 32

load_adme_model_spec:
  module: models.adme.mtl_adme.model
  class: GINRegressor

train_adme_model:
  device: cpu  # or 'cpu' to override
  training_mode: multitask   # multitask | curriculum
  trainer:
    module: models.adme.mtl_adme.training
    function: train
  curriculum:
    strategy: progressive_unfreeze   # options: none | freeze_previous | progressive_unfreeze
    stages:
      - name: physchem
        tasks: [0, 1, 2]
        epochs: 20
      - name: adme
        tasks: [3, 4]
        epochs: 20
      - name: cyp
        tasks: [5, 6, 7, 8]
        epochs: 30
      - name: tox
        tasks: [9]
        epochs: 30
    freeze_shared: false
    reset_optimizer: true
  batch_size: 32
  max_epochs: 100
  patience: 10
  val_fraction: 0.2
  random_seed: 42
  task_weights:
    Solubility: 1.0
    LogP: 1.0
    LogD: 1.0
    Microsomal Stability_Human_mean: 0.9
    CYP3A4_IC50_mean: 0.9
    hERG_IC50_mean: 0.9
  loss:
    type: weighted_mse
    n_bins: 50
    min_weight: 0.3
    max_weight: 5.0
  loss_curve_dir: outputs/mtl_adme/loss_curves 
  model_path: outputs/mtl_adme/models/mtl_adme_best.pth
  predictions_dir: outputs/mtl_adme/preds

  param_grid:
    # lr: [0.001, 0.0005, 0.0001]
    # hidden_dim: [128, 256, 512]
    # num_layers: [4, 5]
    # dropout: [0.1, 0.2]
    lr: [0.0001]
    hidden_dim: [512]
    num_layers: [5]
    dropout: [0.2]

evaluate_adme_model:
  evaluator:
      module: models.adme.mtl_adme.evaluation
      function: evaluate
  eval_plot_dir: outputs/mtl_adme/eval
  predictions_dir: outputs/mtl_adme/preds
  save_plots: true
