task: workflow
workflow_name: active_learning_docking  # workflows/active_learning_docking.py

workflow:
  - prepare_receptor_pdbqt
  - active_learn_docking

options:
  use_conformer_generation: false

backend:
  name: gnina
  executable_path: "/home/corey/local_software/gnina.1.3.2.cuda12.8"
  use_gpu: true

protein:
  pdb_path: "/home/corey/Documents/the_kitbag/pipelines/docking/projects/test/vanilla_docking/5yhl.pdb"
  pH: 7.4

generate_ligands_from_list: true
ligands_txt: "ligs.txt"

active_learning:
  model: random_forest # or LightGBM TODO: add GNN model
  n_cycles: 20 # Number of AL cycles
  n_initial: 20 # initial list of compounds to dock. Bump this 20-50 for production runs.
  batch_size: 20 # initial list of compounds to dock. Bump this 20-50 for production runs.
  scoring: docking_score # TODO: add affinity predictor
  acquisition: uncertainty_sampling  # many options exist here; see modules/utils/acquisition_strategies for all available
  sample_size: 5000 # sample size to predict on and select batch from.  
  seed: 42
  run_random_baseline: true

docking:
  output_dir: "outputs/al_docking_output"
  docking_mode: lowest_energy
  final_n_conformers: 1
  rmsd_threshold: 0.75
  min_energy_gap: 0.5
  n_output_binding_modes: 2
  exhaustiveness: 8
  use_crystal_ligand: true
  size: [15.0, 15.0, 15.0]
