task: workflow
workflow_name: vanilla_docking  # corresponds to workflows/vanilla_docking.py

workflow:
  - prepare_receptor_pdbqt
  - standardise_ligand
  - generate_conformers
  - cluster_conformers
  - save_final_conformers
  - convert_to_pdbqt
  - dock

backend:
  name: unidock
  executable_path: "/usr/local/bin/unidock"
  use_gpu: true

protein:
  pdb_path: "/home/corey/Documents/the_kitbag/pipelines/docking/projects/test/vanilla_docking/5yhl.pdb"
  pH: 7.4

### Ligand prep

# Option 1: Use a file with a simple list of SMILES (ligs.txt). 

# Use with generate_ligands_from_list true to generate the csv of ligands to be parameterised.
# This will generate identifiers for you (lig1, lig2, etc.)

# Option 2: Use a csv with your own identifiers (ligands.csv)

# This will simply use what you give it and propagate the identifiers through the docking.
# TODO: Add capability to add other data (e.g. IC50) to the csv that can be used later.

generate_ligands_from_list: true
ligands_txt: "ligs.txt"    
# ligands_csv: "ligands.csv"

### Docking parameters

# The docking_mode parameter controls whether you dock multiple generated conformers ('ensemble') 
# or just the lowest energy from generated coformers ('lowest_energy').
# rmsd_threshold and min_energy_gap control how many conformers you dock.
# In practice, the parameters below are tight, so only one conformer is generated here anyway. 
# TODO: add actual ensemble docking (multiple proteins) and rename this to something else.

docking:
  output_dir: "output_unidock"
  docking_mode: ensemble # or 'lowest_energy'
  final_n_conformers: 5
  rmsd_threshold: 0.75
  min_energy_gap: 0.5  # in kcal/mol higher = more permissive
  n_output_binding_modes: 2 # MAX number of output poses and is dependent on min_rmsd and energy_range
  exhaustiveness: 8
  min_rmsd: 0.5 # Specific Uni-dock parameter; higher = more permissive on which poses to keep
  energy_range: 3 # Specific Uni-dock parameter; higher = more permissive (units: kcal/mol). Set 9999 to disable.
 
  ### Binding pocket detection
  
  # Option 1: Explicit center
  # center: [10.5, 22.1, 15.7]
  # size: [15.0, 15.0, 15.0]

  # Option 2: Reference ligand path
  # ref_ligand_path: "/path/to/reference_ligand.sdf"
  # size: [15.0, 15.0, 15.0]

  # Option 3: Use crystallized ligand in a 15 x 15 x 15 Angstrom box.
  # TODO: use the output of a pocket finder (e.g. fpocket) to dock into multiple pockets end-to-end.
  use_crystal_ligand: true
  size: [15.0, 15.0, 15.0]

### Docking parameters - extra args

# I just exposed fairly standard args for docking above.
# You can add any of the other Uni-dock args via the 'extra_args' parmeters (commented out for now).
# e.g.

# extra_args:
#   gpu_batch: arg
#   scoring: arg