task: workflow
workflow_name: vanilla_docking  # corresponds to workflows/vanilla_docking.py

workflow:
  - prepare_receptor_pdbqt
  - standardise_ligand
  # - generate_conformers
  # - cluster_conformers
  # - save_final_conformers
  - convert_to_pdbqt
  - dock
  - run_3d_rism

options:
  use_conformer_generation: false

backend:
  name: gnina
  executable_path: "/home/corey/local_software/gnina.1.3.2.cuda12.8"
  use_gpu: true

protein:
  pdb_path: "/home/corey/Documents/ghrepos/the_kitbag/pipelines/docking/projects/test/vanilla_docking/5yhl.pdb"
  pH: 7.4

### Ligand prep

# Option 1: Use a file with a simple list of SMILES (ligs.txt). 

# Use with generate_ligands_from_list true to generate the csv of ligands to be parameterised.
# This will generate identifiers for you (lig1, lig2, etc.)

# Option 2: Use a csv with your own identifiers (ligands.csv)

# This will simply use what you give it and propagate the identifiers through the docking.
# TODO: Add capability to add other data (e.g. IC50) to the csv that can be used later.

generate_ligands_from_list: true
ligands_txt: "ligs_small.txt"    
# ligands_csv: "ligands.csv" 

### Docking parameters - standard

# The docking_mode parameter controls whether you dock multiple generated conformers ('ensemble') 
# or just the lowest energy from generated coformers ('lowest_energy').
# rmsd_threshold and min_energy_gap control how many conformers you dock.
# In practice, the parameters below are tight, so only one conformer is generated here anyway.

docking:
  output_dir: "output_3drism_gnina"
  docking_mode: ensemble # or 'lowest_energy'
  final_n_conformers: 2
  rmsd_threshold: 0.75
  min_energy_gap: 0.5   # in kcal/mol higher = more permissive
  n_output_binding_modes: 1
  exhaustiveness: 8

  ### Binding pocket detection
  
  # Option 1: Explicit center
  # center: [10.5, 22.1, 15.7]
  # size: [15.0, 15.0, 15.0]

  # Option 2: Reference ligand path
  # ref_ligand_path: "/path/to/reference_ligand.sdf"
  # size: [15.0, 15.0, 15.0]

  # Option 3: Use crystallized ligand in a 15 x 15 x 15 Angstrom box.
  use_crystal_ligand: true
  size: [15.0, 15.0, 15.0]

# 3D-RISM specific options
rism:
  solvent: water  # options: water, methanol, ethanol, etc.
  grid_spacing: 0.5  # in Å
  probe_radius: 1.4  # in Å

### Docking parameters - extra args

# I just exposed fairly standard args for docking above.
# You can add any of the other Gnina args via the 'extra_args' parmeters (commented out for now).
# e.g.

# extra_args:
#   cnn_model: arg
#   cnn_rotation: arg