task: workflow
workflow_name: staged_workflow
input_file: inputs/pka_molecules.csv

workflow:
  - site_pka
  - calc_pka

site_pka:
  backend: psi4
  csv_file: ${input_file} 
  output_dir: outputs/site_pka

calc_pka:
  backend: psi4
  site_pka_data_path: outputs/site_pka/site_pka_data.pkl
  method: b3lyp
  basis: def2-svp
  temperature: 298.15
  ram: 8000         # RAM in MB
  ncpu: 16           # number of CPU cores
  # solvent: water ### only in vacuo calculation until I implement Orca
  output_dir: outputs/calc_pka

output:
  directory: outputs/site_pka
  overwrite: true