task: workflow
workflow_name: staged_workflow
input_file: inputs/water.xyz

workflow:
  - optimise
  - qtaim

optimise:
  backend: psi4
  method: b3lyp
  basis: def2-svp
  solvent: water
  ram: 8000        # RAM in MB
  ncpu: 8          # number of CPU cores
  scf_type: pk
  reference: rhf
  maxiter: 50
  output: 
    log: water_opt.log
    energy: water_opt_energy.txt
    geometry: water_opt.xyz
    wfn: water_opt.molden

qtaim:
  backend: multiwfn # TopChem or Critic2 or AIMALL
  ncpu: 16 # the more the better with heavy calculations

output:
  directory: outputs/qtaim
  overwrite: true