task: workflow
workflow_name: staged_workflow
input_file: inputs/water.xyz

workflow:
  - optimise

single_point:
  backend: psi4
  method: bp86
  basis: def2-svp
  output: 
    log: water_spe.log
    energy: water_energy.txt
    geometry: water_spe.xyz

optimise:
  backend: psi4
  method: b3lyp
  basis: def2-svp
  scf_type: pk
  reference: rhf
  maxiter: 50
  output: 
    log: water_opt.log
    energy: water_opt_energy.txt
    geometry: water_opt.xyz

output:
  directory: outputs/optimise
  overwrite: true