name: ml
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      # PyTorch + CUDA
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - --extra-index-url https://download.pytorch.org/whl/cu121

      # PyTorch Geometric and dependencies
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - pyg-lib
      - -f https://data.pyg.org/whl/torch-2.5.1+cu121.html

      # General ML / data stack
      - scikit-learn
      - pandas
      - numpy
      - scipy
      - matplotlib
      - seaborn
      - tqdm
      - tqdm-joblib
      - MDAnalysis
      - networkx
      - joblib
      - requests
      - pyyaml
      - sympy
      - urllib3
      - xxhash
      - yarl
