task: workflow
workflow_name: chembl_multi_target

target_class: rhodopsin
species: "Homo sapiens"
readout: 
  - IC50
  - EC50
relation: "="
assay_type: B

workflow:
  - retrieve_protein_class_target_list
  - retrieve_chembl_bioactivities
  - clean_bioactivities
  - retrieve_compound_smiles
  - annotate_bioactivity_pactivity

output:
  directory: outputs/gpcr_class_a
  filename: class_a_gpcr_bioactivity.csv
  overwrite: true
