task: workflow
workflow_name: chembl_bioactivity_single_target

uniprot_id: P35408
readout: IC50
relation: "="
assay_type: B

workflow:
  - retrieve_chembl_bioactivities
  - clean_bioactivities
  - retrieve_compound_data

output:
  filename: ep4_bioactivity.csv
  directory: outputs/single_target
  overwrite: true
