task: workflow
workflow_name: kindel_del

datasets:
  - name: DDR
    file: ddr1.parquet
  - name: MAPK14
    file: mapk14.parquet


workflow:
  - retrieve_kindel_datasets

s3_prefix: s3://kin-del-2024/data

output:
  directory: outputs/kindel
  overwrite: false
