task: workflow
workflow_name: molecular_dynamics

workflow:
  #- prepare_system
  - setup_simulation
  - minimize
  - heat_and_equilibrate
  - production
  # - post_processing

prepare_system:
  pdb_file: input/5L7I.pdb
  protein_chains: ["A"] # Mandatory; no fallback (yet) if one is not specified. Add as many as necessary / you want to keep. 
  opm_reference: "7X8S"
  opm_align_chain: "A" # chain in your protein you want to align to OPM on
  ligand: # can safely comment out if you don't have a lig.
    resname: VIS
    chain: B
    # RDKit often fails on unusual moieties (inorganics, strained moieties like bicyclo[1.1.1]pentane, cubanes, etc.). 
    # Providing SMILES helps the ligand constructor so it's a good idea.
    # smiles: "CCCCCC" 
  # ligand_file: input/VIS.sdf   # BROKEN DO NOT DO THIS YET
  ligand_parameters: openff-2.0.0.offxml  # Optional but you should set it
  forcefield: ["amber14-all.xml", "amber14/tip3p.xml"] # Optional but you should set it
  ionic_strength: 0.15
  box_padding: 1.0
  membrane: true
  lipid_type: POPC # only for membrane sims
  output_trajectory: "output_multiple_membrane"

setup_simulation: 
  platform: "CUDA" # CPU, if you're crazy. CUDA if you're sane. OpenCL is slower (~ 20-50%) but usable.
  pH: 7.4
  timestep: 2.0  # fs
  temperature: 298  # K
  hmr: true        # Enable Hydrogen Mass Repartitioning
  # friction: 1.0

minimize:
  output_dir: output
  stages:
    - description: "Relaxing lipids"
      k_prot: 1000
      k_lig: 1000
      iter: 2000
      tolerance: 100

    - description: "Relaxing headgroups"
      k_prot: 100
      k_lig: 0
      iter: 5000
      tolerance: 10

    - description: "Global relaxation"
      k_prot: 10
      k_lig: 0
      iter: 2000
      tolerance: 5

    - description: "Final unrestrained minimisation"
      k_prot: 0
      k_lig: 0
      iter: 1000
      tolerance: 1
  progress_update_interval: 5
  diagnostic_interval: 200
  warning_force_threshold: 50000

heat_and_equilibrate:
  heating:
    num_steps: 8
    steps_per_round: 5000 # 5000 for prod
    target_temp: 298
    restraint_strengths: [2.0, 1.5, 1.0, 0.5, 0.25, 0.1, 0.05, 0.0] # number of values here should match num_steps
  equilibration:
    ensemble: NPT
    steps: 100000 # 100000 for prod
    target_temp: 298
    pressure: 1.0
    barostat:
      type: Anisotropic          # Options: MonteCarlo, Anisotropic, Andersen
      frequency: 25             # Attempt volume changes every N steps
      anisotropic: true        # Only used if type=Anisotropic. For membrane sims
    restraint_schedule: [10.0, 5.0, 2.0, 1.0, 0.5, 0.1]
  output_dir: "output_multiple_membrane"

production:
  length_ns: 10                 # total simulation length
  output_frequency: 5000        # Write every 5000 steps (10 ps @ 2 fs timestep)
  output_split_ns: 2            # New trajectory/checkpoint every 2 ns
  output_trajectory: "output_multiple_membrane/trajectory.dcd"
  output_logfile: "output_multiple_membrane/log.txt"

# These steps can optionally be run after simulations or on any sim that's already done. 
# Just comment out previous steps in the workflow above.

post_processing:
  # analysis_components: # add these for the RMSF/F analysis. TODO: consolidate to avoid redundancy.
  #   - name: "GPCR"
  #     chains: ["A"]
  #   - name: "VHH"
  #     chains: ["K"]
  #   - name: "G-protein"
  #     chains: ["B", "C", "D", "E", "F", "G", "H", "I", "J"]
  output_dir: "output_multiple_membrane"
  ligand_resname: "UNK"
  water_resname: "HOH"
  start: 0
  stop: -1
  step: 10 # stride length for the traj. For sims > 5 ns, you'd probably bump this to 100. This is for demonstration purposes.
  trajectory_analysis:
    time_series: ["rmsd", "rmsf", "interactions", "clusters"] # can also run PPI interactions with 'protein_protein_interactions'
    # structural: ["torsions", "ramachandran", "solvent_lifetimes"] WIP
    graph_analyses: ["protein_ligand_communities", "hydration_site_energy", "temporal_motif_persistence", "network_embedding_analysis"]
    # graph_analyses: ["protein_ligand_communities", "hydration_site_energy", "temporal_motif_persistence", "network_embedding_analysis", "protein_protein_network_embedding"]
    # protein_protein_interactions: # only if you actually have a PPI
    #   systems:
    #     - name: "gpcr_vhh"
    #       receptor_chains: ["A"] # GPCR - list all your protein chains here
    #       partner_chains: ["K"] # VHH
    #     - name: "gpcr_gprotein"
    #       receptor_chains: ["A"] # GPCR - list all your protein chains here
    #       partner_chains: ["B", "C", "D", "E", "F", "G", "H", "I", "J"] # G-protein
    #   cutoff: 6.0                   # optional, for contact prefiltering
    #   frequency_cutoff: 0.2   # keep interactions present ≥30% of frames
  solvent_analyses:
    enabled: true
    binding_site_cutoff: 5.0 # distance around the ligand (A) to find hbonds. 
    top_n: 25  # select top N solvent interactions to include on the plot
