# OLD FORMAT - TODO FIX THIS TO BE LIKE THE NEW FORMAT

task: workflow
workflow_name: molecular_dynamics

workflow:
  - prepare_system
  - setup_simulation
  - minimize
  - heat_and_equilibrate
  - production
  # - post_processing

prepare_system:
  pdb_file: input_membrane/5L7I.pdb
  # ligand_file: input/ligand.sdf  # Optional
  ligand_parameters: openff-2.0.0.offxml  # Optional but you should set it
  forcefield: ["amber14-all.xml", "amber14/tip3p.xml"] # Optional
  ionic_strength: 0.15
  box_padding: 1.0
  membrane: true
  lipid_type: POPC # only for membrane sims
  output_trajectory: "output_membrane"

setup_simulation: 
  platform: "OpenCL" # CPU, if you're crazy. CUDA if you're sane. OpenCL is slower (~ 20-50%) but usable.
  pH: 7.0
  timestep: 2.0  # fs
  temperature: 300  # K
  # friction: 1.0

heat_and_equilibrate:
  heating:
    num_steps: 6
    steps_per_round: 5000
    target_temp: 298
    restraint_strengths: [10.0, 5.0, 2.0, 1.0, 0.5, 0.0] # number os values here should match num_steps
  equilibration:
    ensemble: NPT
    steps: 100000
    target_temp: 298
    pressure: 1.0
    barostat:
      type: MonteCarlo          # Options: MonteCarlo, Anisotropic, Andersen
      frequency: 25             # Attempt volume changes every N steps
      anisotropic: true        # Only used if type=Anisotropic. For membrane sims

production:
  length_ns: 10                 # total simulation length
  output_frequency: 5000        # Write every 5000 steps (10 ps at 2 fs timestep)
  output_split_ns: 2            # New trajectory/checkpoint every 2 ns
  output_trajectory: "output_membrane/trajectory.dcd"
  output_logfile: "output_membrane/log.txt"

output:
  overwrite: true