task: workflow
workflow_name: molecular_dynamics

workflow:
  - prepare_system
  - setup_simulation
  - minimize
  - heat_and_equilibrate
  - production
  # - post_processing

prepare_system:
  pdb_file: input/3BGP.pdb
  # ligand_file: input/ligand.sdf  # TODO: Optional
  ligand_parameters: openff-2.0.0.offxml  # Optional but you should set it
  forcefield: ["amber14/protein.ff14SB.xml", "amber14/tip3p.xml"] # Optional but you should set it
  ionic_strength: 0.15
  box_padding: 1.0
  membrane: false
  # lipid_type: POPC # only for membrane sims
  output_trajectory: "output_short"

setup_simulation: 
  platform: "OpenCL" # CPU, if you're crazy. CUDA if you're sane. OpenCL is slower (~ 20-50%) but usable.
  pH: 7.4
  timestep: 2.0  # fs
  temperature: 298  # K
  # friction: 1.0

heat_and_equilibrate:
  heating:
    num_steps: 6
    steps_per_round: 5000
    target_temp: 298
    restraint_strengths: [10.0, 5.0, 2.0, 1.0, 0.5, 0.0]
  equilibration:
    ensemble: NPT
    steps: 100000
    target_temp: 298
    pressure: 1.0
    barostat:
      type: MonteCarlo          # Options: MonteCarlo, Anisotropic, Andersen
      frequency: 25             # Attempt volume changes every N steps
      anisotropic: false        # Only used if type=Anisotropic. For membrane sims

production:
  length_ns: 5
  output_trajectory: "output_short/trajectory.dcd"
  output_logfile: "output_short/log.txt"

# These steps can optionally be run after simulations or on any sim that's already done. 
# Just comment out previous steps above.

post_processing:
  output_dir: "output_short"
  ligand_resname: "UNK"
  water_resname: "HOH"
  start: 0
  stop: -1
  step: 10 # stride length for the traj. For sims > 5 ns, you'd probably bump this to 100. This is for demonstration purposes.
  trajectory_analysis:
    # time_series: ["interactions"]
    time_series: ["rmsd", "rmsf", "interactions"]
    # structural: ["torsions", "ramachandran", "solvent_lifetimes"] WIP
    graph_analyses: ["protein_ligand_communities", "hydration_site_energy", "temporal_motif_persistence", "network_embedding_analysis"]
    # graph_analyses: ["protein_ligand_communities", "hydration_site_energy", "temporal_motif_persistence", "network_embedding_analysis", "protein_protein_network_embedding"]
  solvent_analyses:
    enabled: true
    binding_site_cutoff: 5.0 # distance around the ligand (A) to find hbonds. 
    top_n: 25  # select top N solvent interactions to include on the plot